version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_my_expenses
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: MyExpenses  # Nombre de la base de datos
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_my_expenses
    environment:
      PMA_HOST: mysql
    ports:
      - "8080:80"